use std::fmt::{self, Display};

#[derive(Debug, Clone, Copy)]
#[doc(hidden)]
pub enum HttpCode {
    _110,
    _111,
    _200,
    _301,
    _302,
    _310,
    _400,
    _401,
    _402,
    _403,
    _404,
    _405,
    _406,
    _407,
    _408,
    _409,
    _410,
    _411,
    _412,
    _413,
    _414,
    _415,
    _416,
    _417,
    _418,
    _420,
    _422,
    _423,
    _424,
    _425,
    _426,
    _428,
    _429,
    _431,
    _500,
}

impl Display for HttpCode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(
            f,
            "{}",
            match self {
                HttpCode::_110 => "Connection Timed Out",
                HttpCode::_111 => "Connection refused",
                HttpCode::_200 => "OK",
                HttpCode::_301 => "Moved Permanently",
                HttpCode::_302 => "Found",
                HttpCode::_310 => "Too many redirects",
                HttpCode::_400 => "Bad Request",
                HttpCode::_404 => "Not Found",
                HttpCode::_500 => "Internal Server Error",
                HttpCode::_401 => "Unauthorized",
                HttpCode::_402 => "Payment Required",
                HttpCode::_403 => "Forbidden",
                HttpCode::_405 => "Method Not Allowed",
                HttpCode::_406 => "Not Acceptable",
                HttpCode::_407 => "Proxy Authentication Required",
                HttpCode::_408 => "Request Timeout",
                HttpCode::_409 => "Conflict",
                HttpCode::_410 => "Gone",
                HttpCode::_411 => "Length Required",
                HttpCode::_412 => "Precondition Failed",
                HttpCode::_413 => "Request Entity Too Large",
                HttpCode::_414 => "Request-URI Too Long",
                HttpCode::_415 => "Unsupported Media Type",
                HttpCode::_416 => "Requested Range Not Satisfiable",
                HttpCode::_417 => "Expectation Failed",
                HttpCode::_418 => "I'm a teapot (RFC 2324)",
                HttpCode::_420 => "Enhance Your Calm (Twitter)",
                HttpCode::_422 => "Unprocessable Entity (WebDAV)",
                HttpCode::_423 => "Locked (WebDAV)",
                HttpCode::_424 => "Failed Dependency (WebDAV)",
                HttpCode::_425 => "Reserved for WebDAV",
                HttpCode::_426 => "Upgrade Required",
                HttpCode::_428 => "Precondition Required",
                HttpCode::_429 => "Too Many Requests",
                HttpCode::_431 => "Request Header Fields Too Large",
            }
            .to_string()
        )
    }
}
